### ISSUE TITLE
アプリケーション用と解析用にリポジトリを分けたい

### ISSUE THREAD

**Issue by gtaiyou24** [gtaiyou24/matching_engine#25]
### what
TinderBotを一般用に公開するために、Webアプリケーション開発用のリポジトリとデータの解析用のリポジトリに切り離したい。

### why
データ解析のタスクとしては、

 1. データの収集
 2. データの前処理&基礎分析
 3. モデル構築
 4. アプリケーション側で構築済みモデルを組み込む

ような流れで進むため、変更単位が多い作業1,2,3をいちいちcommit&pushするのは面倒なため。

全員が確認次第、issueをcloseする。

 - [x] @SuguruOoki 
 - [x] @zukako0930

**Comment by SuguruOoki** [comment]
確かに。

**Comment by SuguruOoki** [comment]
欲しいAPIをだいたい言ってくれると助かる！

**Comment by gtaiyou24** [comment]
今日の19時までにTinderBotアプリ版で重視するKPIと機能をドキュメントにまとめてアップします！

**Comment by SuguruOoki** [comment]
@gtaiyou24 ほーい！

**Comment by gtaiyou24** [comment]
dockerの設定で手間取っててまだ少し時間かかります😭

**Comment by SuguruOoki** [comment]
@gtaiyou24 何か詰まっているならこちらでやるから仕様だけくださいな〜！

**Comment by gtaiyou24** [comment]
全員確認したのでclose
